name: test-push
on: push

permissions:
  contents: read
  pull-requests: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  debian-Check:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "1111" > test
          cat test
      - uses: ryaugusta/pr-add-reviewers-action@v1
        with:
          token: ${{ github.token }}
          reviewers: 'kuchune'